export enum InstitutionType {
  PRIMARY_SCHOOL = 'PRIMARY_SCHOOL',
  SECONDARY_SCHOOL = 'SECONDARY_SCHOOL',
  ADVANCED_SECONDARY_SCHOOL = 'ADVANCED_SECONDARY_SCHOOL',
  VOCATIONAL_COLLEGE = 'VOCATIONAL_COLLEGE',
  COLLEGE = 'COLLEGE',
  UNIVERSITY = 'UNIVERSITY'
}

export enum AcademicCycleType {
  TERMS = 'TERMS',
  SEMESTERS = 'SEMESTERS'
}

export enum RoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  HEADMASTER_PRINCIPAL = 'HEADMASTER_PRINCIPAL',
  ACADEMIC_MASTER = 'ACADEMIC_MASTER',
  TEACHER = 'TEACHER',
  LECTURER = 'LECTURER',
  STUDENT = 'STUDENT',
  PARENT_GUARDIAN = 'PARENT_GUARDIAN',
  ACCOUNTANT = 'ACCOUNTANT',
  EXAMINATION_OFFICER = 'EXAMINATION_OFFICER',
  HOD = 'HOD',
  DEAN = 'DEAN',
  REGISTRAR = 'REGISTRAR',
  ADMISSION_OFFICER = 'ADMISSION_OFFICER',
  LIBRARIAN = 'LIBRARIAN',
  ICT_ADMIN = 'ICT_ADMIN',
  ALUMNI = 'ALUMNI'
}

export enum StudentStatus {
  APPLICANT = 'APPLICANT',
  ADMITTED = 'ADMITTED',
  ACTIVE = 'ACTIVE',
  PROMOTED = 'PROMOTED',
  REPEAT = 'REPEAT',
  DEFERRED = 'DEFERRED',
  TRANSFERRED = 'TRANSFERRED',
  COMPLETED = 'COMPLETED',
  GRADUATED = 'GRADUATED',
  WITHDRAWN = 'WITHDRAWN'
}

export enum ExamStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  MARKING = 'MARKING',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED'
}

export enum ResultSubmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  RETURNED = 'RETURNED',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED'
}

export enum ResultApprovalMode {
  OR = 'OR',   // Either Academic Master OR Headmaster can approve
  AND = 'AND'  // Both Academic Master AND Headmaster must approve
}

export enum PublicationScheduleStatus {
  SCHEDULED = 'SCHEDULED',
  PROCESSING = 'PROCESSING',
  PUBLISHED = 'PUBLISHED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED'
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  EXCUSED = 'EXCUSED'
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED'
}

export enum FinancialClearanceStatus {
  CLEARED = 'CLEARED',
  HOLD = 'HOLD',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION'
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  RESULT_RECORDED = 'RESULT_RECORDED',
  RESULT_SUBMITTED = 'RESULT_SUBMITTED',
  RESULT_RETURNED = 'RESULT_RETURNED',
  RESULT_APPROVED = 'RESULT_APPROVED',
  RESULT_SCHEDULED = 'RESULT_SCHEDULED',
  RESULT_PUBLISHED = 'RESULT_PUBLISHED',
  RESULT_CORRECTION_REQUESTED = 'RESULT_CORRECTION_REQUESTED',
  RESULT_CORRECTION_APPROVED = 'RESULT_CORRECTION_APPROVED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  FINANCIAL_CLEARANCE_CHANGED = 'FINANCIAL_CLEARANCE_CHANGED',
  STUDENT_ENROLLED = 'STUDENT_ENROLLED',
  STUDENT_PROMOTED = 'STUDENT_PROMOTED',
  STUDENT_GRADUATED = 'STUDENT_GRADUATED'
}
